Removing redundant "$(LDFLAGS)" fixes undefined
"$(LDFLAGS)" appears twice in these lines and causes the numerous "undefined reference to `sapporo::...`" build problemsin the "tests" directory, therefore removed.